//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handy_Picking_Winform.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANDY_PICKING_MS
    {
        public string CUSTOMER_CODE { get; set; }
        public string PICKING_LIST_NO { get; set; }
        public string DELIVERY_ADDRESS { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string COLUMN1 { get; set; }
        public string COLUMN2 { get; set; }
        public string COLUMN3 { get; set; }
        public string COLUMN4 { get; set; }
        public string COLUMN5 { get; set; }
    }
}
