//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handy_Picking_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANDY_PICKING_DETAIL_LOCK
    {
        public string PICKING_LIST_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public string SALE_ORDER { get; set; }
        public string ITEM_CODE { get; set; }
        public string LOT_ID { get; set; }
        public int QUANTITY { get; set; }
        public string PALLET_NO { get; set; }
        public string SERIES { get; set; }
        public string CUS_ITEM_CODE { get; set; }
        public string TVC_ITEM_CODE { get; set; }
        public string CUSTOMER_PO { get; set; }
        public int QTY_CARTON { get; set; }
        public int QTY_PER_CARTON { get; set; }
        public int QTY_TOTAL { get; set; }
        public decimal NET_WEIGHT { get; set; }
        public decimal NET_WEIGHT_TOTAL { get; set; }
        public decimal GROSS_WEIGHT { get; set; }
        public string LOT_NO { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string COLUMN1 { get; set; }
        public string COLUMN2 { get; set; }
        public string COLUMN3 { get; set; }
        public string COLUMN4 { get; set; }
        public string COLUMN5 { get; set; }
    }
}
