//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handy_Picking_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALLET_MASTER
    {
        public string PALLET_NO { get; set; }
    }
}
