//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handy_Picking_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTMF
    {
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_NAME_E { get; set; }
        public string ITEM_NAME_V { get; set; }
        public string ITEM_CLASSIFY { get; set; }
        public string UNIT_ITEM { get; set; }
        public string CUSTOMER { get; set; }
        public string SUPPLIER { get; set; }
        public Nullable<decimal> LOT_SIZE { get; set; }
        public Nullable<decimal> PRODUCT_DAY { get; set; }
        public Nullable<decimal> SAFETY_STOCK { get; set; }
        public Nullable<decimal> LOSS { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string WEIGHT_UNIT { get; set; }
        public string BOX_TYPE { get; set; }
        public Nullable<decimal> BOX_QUANTITY { get; set; }
        public string BOX_SIZE { get; set; }
        public Nullable<decimal> BOX_WEIGHT { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public string PROCESS_CODE { get; set; }
        public Nullable<decimal> PALLET_WEIGHT { get; set; }
        public Nullable<decimal> BOXPERPALLET_QTY { get; set; }
        public bool DEL_FLAG { get; set; }
        public Nullable<decimal> TOLERANCE { get; set; }
        public string CUS_ITEM_NAME { get; set; }
        public string ACC_ITEM_CODE { get; set; }
    }
}
