//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handy_Picking_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MASTER
    {
        public string PRODUCT_NUMBER { get; set; }
        public string TYPE { get; set; }
        public string REFERENCE { get; set; }
        public string ADDRESS_CODE { get; set; }
        public string EXTERNAL_ITEM_CODE { get; set; }
        public string EXTERNAL_ITEM_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_BY { get; set; }
    }
}
